### ISSUE TITLE
A on a macOS zip'ed tab sample wil be invalid for Teams

### ISSUE THREAD

**Issue by tscholze** [OfficeDev/microsoft-teams-sample-get-started#12]
Hi folks,
if I rezip the untouched sample source with my macOS Sierra (10.12.3) build in zip tool (right click -> compress content), Teams says that it is not able to find the `manifest.json` file. The encoding is still utf-8.
Also alternative zipping tools like "The Unarchiver" is not able to create a zip file that is valid for Teams.

Nevertheless, if I reupload the original zip to Teams, everything works fine.

**Screenshot**
![bildschirmfoto 2017-03-23 um 20 39 03](https://cloud.githubusercontent.com/assets/5583469/24267897/11a40d24-100c-11e7-9672-3d19f60e8ded.png)

If this is not an issue, please help me to find the correct way to zip my tab sample. Thanks!

**Comment by dfederm** [comment]
Can you attach an example zip file which doesn't work?

**Comment by tscholze** [comment]
Hi @dfederm,
thanks for your quick response. I attached a re-zipped sample which I downloaded from: [Github](https://github.com/OfficeDev/microsoft-teams-sample-get-started/blob/master/package/MapsTab.zip).

**Sample Zip**
[MapsTab.zip](https://github.com/OfficeDev/microsoft-teams-sample-get-started/files/868762/MapsTab.zip)

**Comment by dfederm** [comment]
Hey @tscholze, I believe I found the problem. When opening the zip file, I actually notice that there is a MapsTab filder inside, and then the manifest.json is inside that. For sideloading we expect the manifest.json to be at the root inside the zip.

To clarify, the zip you provided has this structure:
- /MapsTab/manifest.json
- /MapsTab/maps44.png
- /MapsTab/maps88.png

instead of
- /manifest.json
- /maps44.png
- /maps88.png

Hope that helps!

**Comment by tscholze** [comment]
Hi @dfederm,
oh my god, this is embarrassing. You are absolutely right!

**Tip for macOS Users:**
Do not click on "compress" of the whole source folder, select all files inside the folder and compress these.
